# Generated by Django 5.1 on 2024-09-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='berserk',
            options={'verbose_name': 'Персонаж берсерка', 'verbose_name_plural': 'Персонажи берсерка'},
        ),
        migrations.AlterField(
            model_name='berserk',
            name='group_name',
            field=models.TextField(verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='berserk',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='berserk',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.group'),
        ),
    ]
