# Generated by Django 5.1 on 2024-09-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0002_group_alter_berserk_options_alter_berserk_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Принадлежность', 'verbose_name_plural': 'Принадлежности'},
        ),
        migrations.RemoveField(
            model_name='berserk',
            name='group_name',
        ),
    ]
