# Generated by Django 5.1 on 2024-09-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0003_alter_group_options_remove_berserk_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerserkArmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Армия',
                'verbose_name_plural': 'Армии',
            },
        ),
        migrations.CreateModel(
            name='BerserkCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Существо',
                'verbose_name_plural': 'Существа',
            },
        ),
        migrations.CreateModel(
            name='BerserkCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('jap_name', models.TextField(verbose_name='Японское имя')),
                ('eng_name', models.TextField(verbose_name='Английское имя')),
                ('qoute', models.TextField(verbose_name='Цитата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.berserkarmy')),
                ('creature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.berserkcreature')),
            ],
            options={
                'verbose_name': 'Персонаж берсерка',
                'verbose_name_plural': 'Персонажи берсерка',
            },
        ),
        migrations.CreateModel(
            name='BerserkArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('harm_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_harm_to', to='berserk.berserkcharacter')),
                ('inventor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_inventor', to='berserk.berserkcharacter')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_owner', to='berserk.berserkcharacter')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакты',
            },
        ),
        migrations.AddField(
            model_name='berserkarmy',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.berserkcharacter'),
        ),
        migrations.CreateModel(
            name='BerserkGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.berserkarmy')),
            ],
            options={
                'verbose_name': 'Местность',
                'verbose_name_plural': 'Местности',
            },
        ),
        migrations.AddField(
            model_name='berserkarmy',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berserk.berserkgeography'),
        ),
    ]
